branches:
  - master
  - release-drafter  # for testing edits to this configuration

name-template: 'Version $NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

categories:
  - title: '### Added:'
    labels:
      - 'changelog/added'
  - title: '### Fixed:'
    labels:
      - 'changelog/fixed'
  - title: '### Improved:'
    labels:
      - 'changelog/improved'
  - title: '### Changed:'
    labels:
      - 'changelog/changed'
  - title: '### Translations:'
    labels:
      - 'changelog/translations'

change-template: '- $TITLE (#$NUMBER)'
template: |
  _Requires CBA version X.Y.Z or later and Arma 3 version X.Y or later._

  $CHANGES

replacers:
  # Category titles
  - search: '/\#\# (\*\*(ADDED|FIXED|IMPROVED|CHANGED|TRANSLATIONS):\*\*)/g'
    replace: '$1'