name = "Cluster Community Assets"
prefix = "cca"
author = "Cluster Mod Team"
mainprefix = "z"

[files]
include = [
    "*.dll",
    "*.so",
    "mod.cpp",
    "README.md",
    "AUTHORS.txt",
    "LICENSE",
    "logo_cca_ca.paa",
    "meta.cpp",
    "addons/ARMSCor_Alouette_III.pbo",
]
exclude = [
    "addons/*/README.md"
]

[version]
git_hash = 0

[asc]
enabled = true
exclude = [
  "dev"
]

[hemtt.config]
preset = "Hemtt"

[hemtt.launch]
workshop = [
    "450814997", # CBA_A3's Workshop ID
    "1888792228", # CCM3s Workshop ID
    "2369477168", # Advanced Developer Tools Workshop ID
    "2183975396", # S & S Workshop ID
    "843425103", # RHS: AFRF Workshop ID
]
parameters = [
    "-skipIntro",
    "-noSplash",
    "-showScriptErrors",
    "-debug",
    "-filePatching",
]
executable = "arma3"